#!/usr/bin/env python
import sys, os

sys.path.insert(0, '.dotbot/lib/pyyaml/lib3')
    
import yaml

CONFIG=".install.conf.yaml"

stream = open(CONFIG, "r")
conf = yaml.safe_load(stream)

for section in conf:
    if 'link' in section:
        for target in section['link']:
            realpath = os.path.expanduser(target)
            if os.path.islink(realpath):
                print("Removing ", realpath)
                os.unlink(realpath)
